### ISSUE TITLE
Certificate Verification warnings

### ISSUE THREAD

**Issue by johannesgreiner** [Qiskit/qiskit-serverless#1454] opened 2024-08-14 09:32 UTC
### Steps to reproduce the problem
A Partner sees a couple of urllib related warnings popping up at use. They do
```
from qiskit_ibm_runtime import NoiseLearner
learner = NoiseLearner(backend, options)
job = learner.run(circuits)
result = job.result()
```
### What is the current behavior?
They get Certificate-related [warnings](https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings) such as
```
micromamba/[...]/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: 
Unverified HTTPS request is being made to host 'api.quantum.ibm.com'. 
Adding certificate verification is strongly advised. 
See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
warnings.warn(
```
### What is the expected behavior?
No warnings

Does this imply CA needs to be added within the Function environment to verify IQP's certificate?

**Comment by Tansito** [comment] 2024-08-16 16:49
Thanks to open this @johannesgreiner , we will take a look. I'm curious about the error because it seems it comes from runtime not from serverless but let us review it and let you know!

**Comment by akihikokuroda** [comment] 2024-08-19 15:21
@johannesgreiner How is the `backend` created?  Thanks!

**Comment by johannesgreiner** [comment] 2024-08-19 19:16
@akihikokuroda can you elaborate your question? They would normally use one of our physical backends. (cc @pacomf)

**Comment by akihikokuroda** [comment] 2024-08-19 19:42
Yes, I understand.  The `backend` in the code snippet must be a python object.  It is created by calling something like:
```
service = QiskitRuntimeService()
backend = service.least_busy(operational=True, simulator=False, min_num_qubits=n_qubits)
```
 There is an option turn off the TLS verification so I just want to make sure that the option is not set.

**Comment by johannesgreiner** [comment] 2024-08-20 14:01
@fpietra can you add some detail on the certification issue you experienced? Is the backend passed as a python object?

**Comment by fpietra** [comment] 2024-08-22 05:14
Thanks a lot for looking into this issue. To call the noise learner, we pass the backend as a python object.
Reading @akihikokuroda's comment and checking how we create the service used for defining the backend, it looks like we are indeed disabling the verification:
```
service = QiskitRuntimeService(token=OUR_TOKEN,
            channel="ibm_quantum",
            instance=OUR_PROJECT,
            verify=False)
backend = service.backend(QPU_NAME)
```
Changing the verification to True stops the InsecureRequestWarnings and the issue is resolved.

**Comment by Tansito** [comment] 2024-08-22 13:35
Thanks @fpietra! I will close this seeing that the problem is solved then. Any concern let us know 😄

**Closed by Tansito** 2024-08-22 13:35 UTC
Labels: bug
